### ISSUE TITLE
Chapter menu not showing in embedded video

### ISSUE THREAD

**Issue by casperrutten** [samlich/peertube-plugin-chapters#1] opened 2021-04-05 19:49 UTC
Wonderfull plugin, just what I needed! Thanks a lot!
The chapter menu is not showing in an embedded video.
Is this a bug, intentionally or am I doing something wrong?

**Comment by samlich** [comment] 2021-04-21 16:30
It is a bug, I forgot to open an issue for it so thanks for doing so.

The problem is that `peertubeHelpers`isn't available for embedded videos, so we cannot get the base URL for retrieving the captions file.

I think it should be possible to get the URL without `peertubeHelpers`. I'm busy right now, but can look into it first week of May.

**Comment by samlich** [comment] 2021-06-29 17:01
Should be fixed in version 1.0.1. It uses the URL from the channel that uploaded the video to find the path to the chapters. Let me know if you find a case where this doesn't work.

**Closed as completed by samlich** 2021-06-29 17:01 UTC
