### ISSUE TITLE
Chapter menu in Firefox not showing full width

### ISSUE THREAD

**Issue by casperrutten** [samlich/peertube-plugin-chapters#2] opened 2021-04-05 19:55 UTC
![peertube-plugin-chapters](https://user-images.githubusercontent.com/17279587/113619467-ea74b800-9650-11eb-95f9-4614d5108d38.png)

I hope it goes well with inserting the image...
In Firefox (87.0)  on Ubuntu the chapter menu is a bit narrowed (see image).
Chrome works well.
Is this a bug?

**Comment by casperrutten** [comment] 2021-04-06 07:48
Its not that in Chrome it works well, its the fact that when I'm logged-in with my account it shows up as in the image. When I logout it shows the right way.

**Comment by samlich** [comment] 2021-04-21 16:38
Hmmm, I think I put a workaround for this, but maybe an update broke it? The relevant code is https://github.com/samlich/peertube-plugin-chapters/blob/master/client/video-watch-client-plugin.js#L53 PeerTube sets the width to 50 px, and I try to set it to `auto`.

It would ultimately be best to figure out why the width is being set to 50 px, rather than just trying to override it. I can look into it first week of May.

**Comment by samlich** [comment] 2021-06-29 13:27
Ok, it's because that line I mentioned above isn't working properly. When I remove the `width:auto;` I see what you posted.

I can't reproduce it, so when logged in, could you please open the developer tools and click the selector icon in the top left, then click on the button which show the chapters menu. It should select a `div` with class `vjs-chapters-button`. Right click and choose Edit as HTML and post that here.

Also check the console and if there's any relevant errors post them.

**Comment by casperrutten** [comment] 2021-06-30 08:09
Thanks for your efforts.
The code in the chapter menu is:
`<span aria-hidden="true" class="vjs-icon-placeholder"></span>`

![afbeelding](https://user-images.githubusercontent.com/17279587/123924728-271b2b80-d982-11eb-85dd-9b2088c35d6b.png)
I've got this error in the console, but I don't know if it concerns your plugin.

**Comment by samlich** [comment] 2021-06-30 15:51
The one I need is actually two levels above the one that gets selected.

![Screenshot_20210630_154340](https://user-images.githubusercontent.com/1349989/123991352-2d2cfe80-d9ba-11eb-8cb6-ab384d0434f1.png)

That error is from a different plugin called `video-annotation`.

**Comment by casperrutten** [comment] 2021-06-30 19:37
`<div class="vjs-chapters-button vjs-menu-button vjs-menu-button-popup vjs-control vjs-button"><button class="vjs-chapters-button vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Hoofdstukken" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Hoofdstukken</span></button><div class="vjs-menu"><ul class="vjs-menu-content" role="menu" style="width: auto;"><li class="vjs-menu-title" tabindex="-1">Hoofdstukken</li><li class="vjs-menu-item" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="false"><span class="vjs-menu-item-text">1e criterium</span><span class="vjs-control-text" aria-live="polite"></span></li><li class="vjs-menu-item" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="false"><span class="vjs-menu-item-text">2e criterium</span><span class="vjs-control-text" aria-live="polite"></span></li><li class="vjs-menu-item" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="false"><span class="vjs-menu-item-text">3e criterium</span><span class="vjs-control-text" aria-live="polite"></span></li></ul></div></div>`

**Comment by samlich** [comment] 2021-07-15 18:00
Sorry, I missed GitHub's notification email.

It look's like the `width: auto` attribute is being added, so it must be that different CSS is needed. If you go to [this `video](https://peertube.milesdewitt.com/videos/watch/b84b56d2-7629-4d2b-8bff-ac6975baddb9), does this happen (you can login as test2/testpassword)? If not, can you link me the video this is happening to. I can't reproduce it on the video linked logged in as either the uploader or a different account.

If you select the `<ul class="vjs-menu-content" role="menu" style="width: auto;">` in the inspector, you can edit the CSS in the column to the right. You could try things like `min-width: 10em`. If something like that works, I can just have the code add it instead.

**Comment by samlich** [comment] 2022-09-23 19:54
The `width: auto` change seems to now longer be required as of one of the video.js updates, so I'm going to assume this is fixed now. But, if not, let me know.

**Closed as completed by samlich** 2022-09-23 19:54 UTC
